binary_sensor:
  - platform: template
    sensors:

      laundry_washer_running:
        friendly_name: "Laundry Washer Running"
        delay_off: '00:05:00'
        value_template: "{{
           states('sensor.iotawatt_input_washer') | int(0) > 75
        }}"

