input_text:

  clothes_dryer:
    # Possible states:
    # -Idle (not in use, possibly occupied)
    # -Indeterminate (possibly loading/unloading)
    # -Running
    # -Completed (finished, not empty)
    name: 'Clothes Dryer'
    initial: 'Initializing'


# to expose the text status read-only
sensor:
  - platform: template
    sensors:
      clothes_dryer:
        friendly_name: 'Clothes Dryer'
        icon_template: mdi:tumble-dryer
        value_template: "{{ states('input_text.clothes_dryer') }}"


automation:

###############################
# Clothes Dryer State Machine #
###############################

  - alias: "Dryer > Indeterminate"
    # Maybe loading
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_dryer_door
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.laundry_dryer_door
        from: 'on'
        to: 'off'
      - platform: homeassistant
        event: start
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.clothes_dryer
        data:
          value: 'Indeterminate'

  - alias: "Dryer Indeterminate Timeout > Idle"
    # Assume it was bumped, make idle
    trigger:
      - platform: state
        entity_id: input_text.clothes_dryer
        to: 'Indeterminate'
        for: '00:05:00'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.clothes_dryer
        data:
          value: 'Idle'

  - alias: "Dryer > Running"
    # Move to running
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_dryer_running
        to: 'on'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.clothes_dryer
        data:
          value: 'Running'

  - alias: "Dryer Running > Completed"
    # If it's stopped running, and door is not opened, move to completed
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_dryer_running
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.laundry_dryer_door
        state: 'off'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.clothes_dryer
        data:
          value: 'Completed'

  - alias: "Dryer Completed Timeout > Idle"
    # If it's been at Completed too long, reset to idle
    trigger:
      - platform: state
        entity_id: input_text.clothes_dryer
        to: 'Completed'
        for: '23:00:00'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.clothes_dryer
        data:
          value: 'Idle'

