input_text:

  washing_machine:
    # Possible states:
    # -Idle (not in use, possibly occupied)
    # -Indeterminate (possibly loading/unloading)
    # -Running
    # -Completed (finished, not empty)
    # -Door_Shut_Alarm (warning that door is left shut getting funky)
    name: 'Washing Machine'
    initial: 'Initializing'

# to expose the text status read-only
sensor:
  - platform: template
    sensors:
      washing_machine:
        friendly_name: 'Washing Machine'
        icon_template: >-
          {% if is_state('input_text.washing_machine','Door_Shut_Alarm') %}
          mdi:washing-machine-alert
          {% else %}
          mdi:washing-machine
          {% endif %}
        value_template: "{{ states('input_text.washing_machine') }}"


automation:

#################################
# Washing Machine State Machine #
#################################

  - alias: "Washer > Indeterminate"
    # Maybe bumped, maybe loading, maybe started
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_washer_door
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: binary_sensor.laundry_washer_door
        from: 'off'
        to: 'on'
      - platform: template
        value_template: "{{ is_state('binary_sensor.laundry_washer_door','on') and is_state('input_text.washing_machine','Completed') }}"
      - platform: homeassistant
        event: start
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.washing_machine
        data:
          value: 'Indeterminate'

  - alias: "Washer Indeterminate Timeout > Idle"
    # Assume it was bumped, make idle
    trigger:
      - platform: state
        entity_id: input_text.washing_machine
        to: 'Indeterminate'
        for: '00:10:00'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.washing_machine
        data:
          value: 'Idle'

  - alias: "Washer > Running"
    # Move to running
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_washer_running
        to: 'on'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.washing_machine
        data:
          value: 'Running'

  - alias: "Washer Running > Completed"
    # If it's off for longer than cycle pause, and still off, move to completed
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_washer_running
        from: 'on'
        to: 'off'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.washing_machine
        data:
          value: 'Completed'

  - alias: "Washer Completed Timeout > Idle"
    # If it's been at Completed too long, reset to idle
    trigger:
      - platform: state
        entity_id: input_text.washing_machine
        to: 'Completed'
        for: '08:00:00'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.washing_machine
        data:
          value: 'Idle'

  - alias: "Washer > Door_Shut_Alarm"
    # Door Shut Too Long while idle
    trigger:
      - platform: state
        entity_id: input_text.washing_machine
        to: 'Idle'
    condition:
      - condition: state
        entity_id: binary_sensor.laundry_washer_door
        state: 'off'
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.washing_machine
        data:
          value: 'Door_Shut_Alarm'
